tabWidth: 2
useTabs: false
singleQuote: true
quoteProps: 'preserve'
bracketSpacing: true
bracketSameLine: false
endOfLine: 'lf'
semi: false
overrides:
  - files: '**/*.{ps,js,ts}'
    options:
      semi: true